version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: devise_invitable
    versions:
    - 2.0.3
    - 2.0.4
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: geocoder
    versions:
    - 1.6.4
    - 1.6.5
    - 1.6.6
  - dependency-name: rails
    versions:
    - 4.2.11.1
    - 6.0.3.5
  - dependency-name: database_cleaner
    versions:
    - 1.8.5
    - 2.0.0
