source 'https://rubygems.org'

ruby '2.4.2'
gem 'rails', '~> 4.2', '>= 4.2.7.1'
gem 'pg', '0.20'
gem 'devise', '~> 3.5', '>= 3.5.10'
gem 'devise_invitable', '~> 1.6', '>= 1.6.1'
gem 'heroku-api'
gem 'sprockets', '~> 2.11', '>= 2.11.3'
gem 'fullcalendar-rails'
gem 'momentjs-rails'
gem 'jbuilder'

group :development, :test do
  gem 'timecop'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'simplecov'
  gem 'sinatra'
  gem 'rspec-rails'
  gem 'rspec-activemodel-mocks'
  gem 'execjs'
  gem 'aruba'
  gem 'byebug'
  gem 'rack_session_access'
  gem 'jasmine', '~> 2.4'
  gem 'jasmine-jquery-rails', '2.0.2'
  gem 'binding_of_caller'
end

group :development do
  gem 'rubocop-git'
  gem 'letter_opener'
  gem 'railroady'
  gem 'quiet_assets'
end

group :test do
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels'
  gem 'capybara'
  gem 'capybara-webkit', :git => 'https://github.com/thoughtbot/capybara-webkit', :branch => 'master'
  gem 'nokogiri'
  gem 'factory_bot_rails'
  gem 'webmock'
  gem 'uri-handler'
  gem 'selenium'
  gem 'selenium-client'
  gem 'coveralls'
  gem 'shoulda'
  gem 'vcr'
  gem 'puffing-billy'
  gem 'poltergeist'
  gem 'phantomjs', :require => 'phantomjs/poltergeist'
  gem 'show_me_the_cookies'
end

group :production do
  gem 'rails_12factor'
  gem 'newrelic_rpm'
end

gem 'coffee-rails'
gem 'uglifier', '~> 3.0', '>= 3.0.3'
gem 'sass-rails', '~> 4.0', '>= 4.0.5'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'font-awesome-rails'
gem 'jquery-rails'
gem 'bootstrap_sortable_rails', '~> 0.1.3'
gem 'breadcrumbs_on_rails'
gem 'bootstrap-datepicker-rails'
gem 'therubyracer'
gem 'underscore-rails'
gem 'geocoder'
gem 'unicorn'
gem 'redcarpet'
gem 'url_validator', git: 'https://github.com/AgileVentures/url_validator.git'
gem 'httparty'
gem 'sucker_punch', '~> 2.0' # async job
gem 'rails_autolink'
gem 'paranoia', '~> 2.0'
gem 'dotenv-rails'
gem 'figaro'
gem 'airbrake'
gem 'friendly_id', '~> 5.1.0'
gem 'meta-tags'
