source 'https://rubygems.org'

ruby '2.4.2'
gem 'rails', '~> 5.1', '>= 5.1.4'
gem 'pg'
gem 'devise'
gem 'devise_invitable'
gem 'heroku-api'
gem 'sprockets'
gem 'fullcalendar-rails'
gem 'momentjs-rails'
gem 'jbuilder'
gem 'coffee-rails'
gem 'uglifier'
gem 'sass-rails'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'font-awesome-rails'
gem 'jquery-rails'
gem 'bootstrap_sortable_rails'
gem 'breadcrumbs_on_rails'
gem 'bootstrap-datepicker-rails'
gem 'therubyracer'
gem 'underscore-rails'
gem 'geocoder'
gem 'unicorn'
gem 'redcarpet'
gem 'url_validator', git: 'https://github.com/AgileVentures/url_validator.git', branch: 'master'
gem 'httparty'
gem 'sucker_punch'
gem 'rails_autolink'
gem 'paranoia'
gem 'dotenv-rails'
gem 'figaro'
gem 'airbrake'
gem 'friendly_id'
gem 'meta-tags'

group :development, :test do
  gem 'timecop'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'simplecov'
  gem 'sinatra'
  gem 'rspec-rails'
  gem 'rspec-activemodel-mocks'
  gem 'execjs'
  gem 'aruba'
  gem 'byebug'
  gem 'rack_session_access'
  gem 'jasmine'
  gem 'jasmine-jquery-rails'
  gem 'binding_of_caller'
end

group :development do
  gem 'rubocop-git'
  gem 'letter_opener'
  gem 'railroady'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'cucumber-rails-training-wheels'
  gem 'capybara'
  gem 'capybara-webkit', git: 'https://github.com/thoughtbot/capybara-webkit', branch: 'master'
  gem 'nokogiri'
  gem 'factory_bot_rails'
  gem 'webmock'
  gem 'uri-handler'
  gem 'selenium'
  gem 'selenium-client'
  gem 'coveralls'
  gem 'shoulda'
  gem 'vcr'
  gem 'puffing-billy'
  gem 'poltergeist'
  gem 'phantomjs', require: 'phantomjs/poltergeist'
  gem 'show_me_the_cookies'
end

group :production do
  gem 'rails_12factor'
  gem 'newrelic_rpm'
end
