# added require to std_opts: http://stackoverflow.com/a/6829369/2197402

<%
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --require features/ --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
first_try:  NEVER_FAIL=true  <%= std_opts %> --format rerun --out rerun.txt features
second_try: NEVER_FAIL=false <%= std_opts %> @rerun.txt
